### ISSUE TITLE
Property 'suffix' does not exist on type 'MapStoresCustomization' on build

### ISSUE THREAD

**Issue by Rusinas** [posva/pinia#1812]
### Reproduction

-

### Steps to reproduce the bug

Trying to build my project with Pinia in it, then I got the errors from vue-tsc

```
> vue-tsc --noEmit && vite build

node_modules/pinia/dist/pinia.d.ts:576:132 - error TS2339: Property 'suffix' does not exist on type 'MapStoresCustomization'.

576 export declare function setMapStoreSuffix(suffix: MapStoresCustomization extends Record<'suffix', string> ? MapStoresCustomization['suffix'] : string): void;
                                                                                                                                       ~~~~~~~~

node_modules/pinia/dist/pinia.d.ts:643:102 - error TS2339: Property 'suffix' does not exist on type 'MapStoresCustomization'.

643     [Id in `${Ids}${MapStoresCustomization extends Record<'suffix', string> ? MapStoresCustomization['suffix'] : 'Store'}`]: () => Store<Id extends `${infer RealId}${MapStoresCustomization extends Record<'suffix', string> ? MapStoresCustomization['suffix'] : 'Store'}` ? RealId : string, State, Getters, Actions>;
                                                                                                         ~~~~~~~~

node_modules/pinia/dist/pinia.d.ts:643:248 - error TS2339: Property 'suffix' does not exist on type 'MapStoresCustomization'.

643     [Id in `${Ids}${MapStoresCustomization extends Record<'suffix', string> ? MapStoresCustomization['suffix'] : 'Store'}`]: () => Store<Id extends `${infer RealId}${MapStoresCustomization extends Record<'suffix', string> ? MapStoresCustomization['suffix'] : 'Store'}` ? RealId : string, State, Getters, Actions>;
                                                                                                                                                                                                                                                           ~~~~~~~~


Found 3 errors in the same file, starting at: node_modules/pinia/dist/pinia.d.ts:576
```

### Expected behavior

Build normally

### Actual behavior

Doesn't build

### Additional information

This started to happen after updating to 2.0.24. On previous version everything was fine
