### ISSUE TITLE
@pinia/nuxt v0.11.3 breaking change: storesDirs resolution changed for Nuxt 4 projects

### ISSUE THREAD

**Issue by cborje** [posva/pinia#3086]
### Reproduction

.

### Steps to reproduce the bug

.

### Expected behavior

.

### Actual behavior

.

### Additional information

After upgrading from `@pinia/nuxt` 0.11.2 to 0.11.3, store auto-imports stopped working entirely in our Nuxt 4 project.

## Environment

- `@pinia/nuxt`: 0.11.3 (worked in 0.11.2)
- `nuxt`: 4.2.2
- Using new Nuxt 4 app directory structure

## The Problem

In 0.11.3, the `storesDirs` resolution logic changed. The module now resolves paths against `layer.app` instead of `srcDir`:

```ts
// module.ts - 0.11.3
for (const storeDir of options.storesDirs) {
  for (const layer of layers) {
    addImportsDir(resolve(layer.app, storeDir))
  }
}
```

This is a breaking change for Nuxt 4 projects that had configured `storesDirs` with the app prefix:

```ts
// nuxt.config.ts - worked in 0.11.2, broken in 0.11.3
pinia: {
  storesDirs: ['./app/stores/**', './app/stores-old/**'],
}
```

In 0.11.3, this resolves to `app/app/stores/**` (double app prefix), causing no stores to be found and all store auto-imports to fail silently.

## Workaround

Remove the app prefix from `storesDirs`:

```ts
pinia: {
  storesDirs: ['./stores/**', './stores-old/**'],
}
```

## Impact

This caused our production build to fail with cryptic "Cannot find name 'useXxxStore'" errors across dozens of files. The silent failure (no warning when storesDirs resolves to non-existent paths) made debugging difficult.
