### ISSUE TITLE
Issue happening when migrating from @pinia/nuxt 0.4.8 to 0.11.0

### ISSUE THREAD

**Issue by anviksuteiriy** [posva/pinia#2986]
### Reproduction

Just updated the package and when ran npm run build it starts breaking 

### Steps to reproduce the bug

we are using @pinia/nuxt which we tried to upgrade from 0.4.8 to 0.11.0 and ran npm run build and all nuxt pages are now not working and giving below error, checked all the store configurations given in pinia docs but all in vein can any one help on this 

`[request error] [unhandled] [GET] http://localhost:3000/__nuxt_error?error=true&url=%2Fen%2Fstock%2F&statusCode=500&statusMessage=Server+Error&message=Cannot+read+properties+of+undefined+(reading+%27default%27)
 TypeError: obj.hasOwnProperty is not a function
    at shouldHydrate (/home/anantsingh/Documents/BasParts/nuxter/.output/server/node_modules/pinia/dist/pinia.prod.cjs:232:40)
    ... 8 lines matching cause stack trace ...
    at async Object.handler (file:///home/anantsingh/Documents/BasParts/nuxter/.output/server/chunks/nitro/nitro.mjs:1876:19) {
  cause: TypeError: obj.hasOwnProperty is not a function
      at shouldHydrate (/home/anantsingh/Documents/BasParts/nuxter/.output/server/node_modules/pinia/dist/pinia.prod.cjs:232:40)
      at file:///home/anantsingh/Documents/BasParts/nuxter/.output/server/chunks/build/server.mjs:739:16
      at flatten (file:///home/anantsingh/Documents/BasParts/nuxter/.output/server/node_modules/devalue/src/stringify.js:63:18)
      at flatten (file:///home/anantsingh/Documents/BasParts/nuxter/.output/server/node_modules/devalue/src/stringify.js:200:43)
      at flatten (file:///home/anantsingh/Documents/BasParts/nuxter/.output/server/node_modules/devalue/src/stringify.js:65:39)
      at stringify (file:///home/anantsingh/Documents/BasParts/nuxter/.output/server/node_modules/devalue/src/stringify.js:212:16)
      at renderPayloadJsonScript (file:///home/anantsingh/Documents/BasParts/nuxter/.output/server/chunks/routes/renderer.mjs:187:32)
      at Object.render (file:///home/anantsingh/Documents/BasParts/nuxter/.output/server/chunks/routes/renderer.mjs:344:15)
      at async Object.handler (file:///home/anantsingh/Documents/BasParts/nuxter/.output/server/chunks/nitro/nitro.mjs:8451:22)
      at async Object.handler (file:///home/anantsingh/Documents/BasParts/nuxter/.output/server/chunks/nitro/nitro.mjs:1876:19),
  statusCode: 500,
  fatal: false,
  unhandled: true,
  statusMessage: undefined,
  data: undefined
}
`

### Expected behavior

page should work like normal as it was running before using npm run build

### Actual behavior

Pages were running normal before upgrade
