### ISSUE TITLE
Problems with Nuxt 3.0.0

### ISSUE THREAD

**Issue by misterproton** [posva/pinia#1829]
### Reproduction

Simple modification of Nuxt Stackblitz demo

### Steps to reproduce the bug

Trying to get this to work on Nuxt 3.0.0 release, and am stuck.  You have a published StackBlitz demo but it's for RC13.  Update the repo by:

1. Change package.json requirement to: "nuxt": "3.0.0"
2. Try to run the app.  You will get an error "ERROR  Cannot start nuxt:  _nuxt.defineNuxtConfig is not a function" but this is not the main issue.
3. Change nuxt.config.ts by removing the line: "import { defineNuxtConfig } from 'nuxt'".  It seems you are supposed to do this now on the 3.0.0 release?
4. Attempt to run the app again.

### Expected behavior

I would like to see Pinia in my DevTools.

### Actual behavior

Nuxt fails, with this error message.

[🍍]: getActivePinia was called with no active Pinia. Did you forget to install pinia? const pinia = createPinia() app.use(pinia) This will fail in production.

**Comment by posva** [comment]
Released a new version and fixed the example

**Comment by misterproton** [comment]
Thank you sir!  I was able to get it to work in my environment.

FYI -- https://nuxt.com/docs/getting-started/configuration

> A minimal configuration file exports the defineNuxtConfig function 
> containing an object with your configuration. The defineNuxtConfig 
> helper is globally available without import.

You should probably update the StackBlitz demo to use 3.0.0 also.

**Comment by posva** [comment]
ah, nice, thanks!
